# Generated by Django 2.0.6 on 2018-06-14 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 8, 53, 21, 722478, tzinfo=utc), verbose_name='Fecha de Publicación'),
        ),
    ]
